# Generated by Django 4.0.3 on 2022-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='Field',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Network Engineering', 'Network Engineering'), ('User Support', 'User Support'), ('Project Management', 'Project Management'), ('Web Development', 'Web Development'), ('Information Security', 'Information Security'), ('Systems Architecture', 'System Architecture'), ('Database Administration', 'Database Administration'), ('Systems Administration', 'Systems Administration')], default='Software Development', max_length=30),
        ),
    ]
